PROPERTIES = [
    {
        'id': '1',
        'type': 'Condo',
        'address': '262 Dundas St E, Waterdown, Ontario L8B 0L1',
        'city': 'Waterdown',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/262-dundas-st-e%2C-waterdown%2C-ontario-l8b-0l1',
        'description': 'Condo available for rent in Waterdown.',
    },
    {
        'id': '2',
        'type': 'Detached House',
        'address': '43 McFarlane Dr, Cambridge, Ontario N3C 4J9',
        'city': 'Cambridge',
        'availability': 'For Lease',
        'price': '2950',
        'beds': '3.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/43-mcfarlane-dr%2C-cambridge%2C-ontario-n3c-4j9',
        'description': 'Detached House available for rent in Cambridge.',
    },
    {
        'id': '3',
        'type': 'Basement Apartment',
        'address': '2-746 Phillip Murray Ave, Oshawa, Ontario L1J 1J3',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-746-phillip-murray-ave%2C-oshawa%2C-ontario-l1j-1j3',
        'description': 'Basement Apartment available for rent in Oshawa.',
    },
    {
        'id': '4',
        'type': 'Detached House',
        'address': '3351 Willguard Ct, Niagara Falls, Ontario L2G 6X6',
        'city': 'Niagara Falls',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3351-willguard-ct%2C-niagara-falls%2C-ontario-l2g-6x6',
        'description': 'Detached House available for rent in Niagara Falls.',
    },
    {
        'id': '5',
        'type': 'Apartment',
        'address': '1-13854 Bathurst Street, King, Ontario L7B 1K5',
        'city': 'King',
        'availability': 'For Lease',
        'price': '2195',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-13854-bathurst-street%2C-king%2C-ontario-l7b-1k5',
        'description': 'Apartment available for rent in King.',
    },
    {
        'id': '6',
        'type': 'Apartment',
        'address': '204-12 Anglesey Blvd, Toronto, Ontario M9A 3B3',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '1875',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/204-12-anglesey-blvd%2C-toronto%2C-ontario-m9a-3b3',
        'description': 'Apartment available for rent in Toronto.',
    },
    {
        'id': '7',
        'type': 'Basement Apartment',
        'address': '2-137 Gardenpost Ter, Ottawa, Ontario K4A 5G9',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1750',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-137-gardenpost-ter%2C-ottawa%2C-ontario-k4a-5g9',
        'description': 'Basement Apartment available for rent in Ottawa.',
    },
    {
        'id': '8',
        'type': 'Property',
        'address': '108-1459 Trafalgar St, London, Ontario N5W 1W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1450',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/108-1459-trafalgar-st%2C-london%2C-ontario-n5w-1w8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '9',
        'type': 'Property',
        'address': '2-18 Langton Rd, London, Ontario N5V 2L8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1650',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-18-langton-rd%2C-london%2C-ontario-n5v-2l8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '10',
        'type': 'Condo',
        'address': '1105-1 Jarvis St, Hamilton, Ontario L8R 3J2',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '2095',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1105-1-jarvis-st%2C-hamilton%2C-ontario-l8r-3j2',
        'description': 'Condo available for rent in Hamilton.',
    },
    {
        'id': '11',
        'type': 'Basement Apartment',
        'address': '2-133 Marchington Cir, Scarborough, Ontario M1R 3M9',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-133-marchington-cir%2C-scarborough%2C-ontario-m1r-3m9',
        'description': 'Basement Apartment available for rent in Scarborough.',
    },
    {
        'id': '12',
        'type': 'Condo',
        'address': 'N701-35 Rolling Mills Road, Toronto, Ontario M5A 0V6',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/n701-35-rolling-mills-road%2C-toronto%2C-ontario-m5a-0v6',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '13',
        'type': 'Basement Apartment',
        'address': '2-11 Northern Breeze Cres, Whitby, Ontario L1R 0P4',
        'city': 'Whitby',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-11-northern-breeze-cres%2C-whitby%2C-ontario-l1r-0p4',
        'description': 'Basement Apartment available for rent in Whitby.',
    },
    {
        'id': '14',
        'type': 'Property',
        'address': '1-484 Main St E, Hamilton, Ontario L8N 1K6',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-484-main-st-e%2C-hamilton%2C-ontario-l8n-1k6',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '15',
        'type': 'Property',
        'address': '3-142 Brock St, Brockville, Ontario K6V 4G4',
        'city': 'Brockville',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-142-brock-st%2C-brockville%2C-ontario-k6v-4g4',
        'description': 'Property available for rent in Brockville.',
    },
    {
        'id': '16',
        'type': 'Detached House',
        'address': '33 Medley Ln, Ajax, Ontario L1S 3P5',
        'city': 'Ajax',
        'availability': 'For Lease',
        'price': '2875',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/33-medley-ln%2C-ajax%2C-ontario-l1s-3p5',
        'description': 'Detached House available for rent in Ajax.',
    },
    {
        'id': '17',
        'type': 'Basement Apartment',
        'address': '2-102 Tozer Crescent, Ajax, Ontario L1T 5A2',
        'city': 'Ajax',
        'availability': 'For Lease',
        'price': '1750',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-102-tozer-crescent%2C-ajax%2C-ontario-l1t-5a2',
        'description': 'Basement Apartment available for rent in Ajax.',
    },
    {
        'id': '18',
        'type': 'Detached House',
        'address': '2061 St Paul Rd, Innisfil Beach, Ontario L9S 1V2',
        'city': 'Innisfil Beach',
        'availability': 'For Lease',
        'price': '2995',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2061-st-paul-rd%2C-innisfil-beach%2C-ontario-l9s-1v2',
        'description': 'Detached House available for rent in Innisfil Beach.',
    },
    {
        'id': '19',
        'type': 'Apartment',
        'address': '2-823 Stirling Ave S, Kitchener, Ontario N2M 3K4',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '2299',
        'beds': '3',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-823-stirling-ave-s%2C-kitchener%2C-ontario-n2m-3k4',
        'description': 'Apartment available for rent in Kitchener.',
    },
    {
        'id': '20',
        'type': 'Property',
        'address': '1-5270 Buchanan Ave, Niagara Falls, Ontario L2E 5A8',
        'city': 'Niagara Falls',
        'availability': 'For Lease',
        'price': '1995',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-5270-buchanan-ave%2C-niagara-falls%2C-ontario-l2e-5a8',
        'description': 'Property available for rent in Niagara Falls.',
    },
    {
        'id': '21',
        'type': 'Basement Apartment',
        'address': "2-3187 O'Hagan Dr, Mississauga, Ontario L5C 2C4",
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '1',
        'baths': '1',
        'url': "https://www.qterrapropertymanagement.com/properties/2-3187-o'hagan-dr%2C-mississauga%2C-ontario-l5c-2c4",
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '22',
        'type': 'Basement Apartment',
        'address': '2-14 Marcel Brunelle Dr, Whitby, Ontario L1P 0G9',
        'city': 'Whitby',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-14-marcel-brunelle-dr%2C-whitby%2C-ontario-l1p-0g9',
        'description': 'Basement Apartment available for rent in Whitby.',
    },
    {
        'id': '23',
        'type': 'Property',
        'address': '3-527 Barton St E, Hamilton, Ontario L8L 2Y9',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-527-barton-st-e%2C-hamilton%2C-ontario-l8l-2y9',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '24',
        'type': 'Condo',
        'address': '326-20 All Nations Dr, Brampton, Ontario L7A 5M5',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2050',
        'beds': '1.5',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/326-20-all-nations-dr%2C-brampton%2C-ontario-l7a-5m5',
        'description': 'Condo available for rent in Brampton.',
    },
    {
        'id': '25',
        'type': 'Apartment',
        'address': '197 Louisa St, Ottawa, Ontario K1R 6Y9',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1690',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/197-louisa-st%2C-ottawa%2C-ontario-k1r-6y9',
        'description': 'Apartment available for rent in Ottawa.',
    },
    {
        'id': '26',
        'type': 'Townhouse',
        'address': '3050 Rotary Way, Burlington, Ontario L7M 0G8',
        'city': 'Burlington',
        'availability': 'For Lease',
        'price': '3050',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3050-rotary-way%2C-burlington%2C-ontario-l7m-0g8',
        'description': 'Townhouse available for rent in Burlington.',
    },
    {
        'id': '27',
        'type': 'Condo',
        'address': '802-461 Green Rd, Stoney Creek, Ontario L8E 5B4',
        'city': 'Stoney Creek',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/802-461-green-rd%2C-stoney-creek%2C-ontario-l8e-5b4',
        'description': 'Condo available for rent in Stoney Creek.',
    },
    {
        'id': '28',
        'type': 'Condo',
        'address': '218-60 Honeycrisp Cres, Concord, Ontario L4K 0N5',
        'city': 'Concord',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/218-60-honeycrisp-cres%2C-concord%2C-ontario-l4k-0n5',
        'description': 'Condo available for rent in Concord.',
    },
    {
        'id': '29',
        'type': 'Basement Apartment',
        'address': '5-210 Armstrong St, Ottawa, Ontario K1Y 2W4',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/5-210-armstrong-st%2C-ottawa%2C-ontario-k1y-2w4',
        'description': 'Basement Apartment available for rent in Ottawa.',
    },
    {
        'id': '30',
        'type': 'Property',
        'address': '1-1978 Dufferin St, Toronto, Ontario M6E 3R1',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '3395',
        'beds': '4',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-1978-dufferin-st%2C-toronto%2C-ontario-m6e-3r1',
        'description': 'Property available for rent in Toronto.',
    },
    {
        'id': '31',
        'type': 'Basement Apartment',
        'address': '2-2458 Linwood St, Pickering, Ontario L1X 2N8',
        'city': 'Pickering',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '1.5',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-2458-linwood-st%2C-pickering%2C-ontario-l1x-2n8',
        'description': 'Basement Apartment available for rent in Pickering.',
    },
    {
        'id': '32',
        'type': 'Condo',
        'address': '228-4K Spadina Ave., Toronto, Ontario M5V 3Y9',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/228-4k-spadina-ave.%2C-toronto%2C-ontario-m5v-3y9',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '33',
        'type': 'Property',
        'address': '1-55 Crawford Dr, Brampton, Ontario L6V 2C6',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-55-crawford-dr%2C-brampton%2C-ontario-l6v-2c6',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '34',
        'type': 'Detached House',
        'address': '1-70 Boundbrook Dr, Brampton, Ontario L7A 0L9',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2499',
        'beds': '4',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-70-boundbrook-dr%2C-brampton%2C-ontario-l7a-0l9',
        'description': 'Detached House available for rent in Brampton.',
    },
    {
        'id': '35',
        'type': 'Condo',
        'address': '410-2 Manderley Dr, Scarborough, Ontario M1N 1R6',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '1.5',
        'baths': '3',
        'url': 'https://www.qterrapropertymanagement.com/properties/410-2-manderley-dr%2C-scarborough%2C-ontario-m1n-1r6',
        'description': 'Condo available for rent in Scarborough.',
    },
    {
        'id': '36',
        'type': 'Detached House',
        'address': '459 N Service Road, Mississauga, Ontario L5A 1B1',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '3695',
        'beds': '4.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/459-n-service-road%2C-mississauga%2C-ontario-l5a-1b1',
        'description': 'Detached House available for rent in Mississauga.',
    },
    {
        'id': '37',
        'type': 'Condo',
        'address': '2005-284 King St E, Toronto, Ontario M5A 1K4',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '2',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2005-284-king-st-e%2C-toronto%2C-ontario-m5a-1k4',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '38',
        'type': 'Property',
        'address': '1-95 Rockwell Ave, Toronto, Ontario M6N 1N9',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-95-rockwell-ave%2C-toronto%2C-ontario-m6n-1n9',
        'description': 'Property available for rent in Toronto.',
    },
    {
        'id': '39',
        'type': 'Property',
        'address': '2-200 Chaffey St, Welland, Ontario L3B 2Y5',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '1',
        'baths': '3.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-200-chaffey-st%2C-welland%2C-ontario-l3b-2y5',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '40',
        'type': 'Basement Apartment',
        'address': 'GS3-261 Dixon St, Kitchener, Ontario N2G 3G1',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '1650',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/gs3-261-dixon-st%2C-kitchener%2C-ontario-n2g-3g1',
        'description': 'Basement Apartment available for rent in Kitchener.',
    },
    {
        'id': '41',
        'type': 'Detached House',
        'address': '116 Parkview Hill Crescent, East York, Ontario M4B 1R4',
        'city': 'East York',
        'availability': 'For Lease',
        'price': '3450',
        'beds': '3',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/116-parkview-hill-crescent%2C-east-york%2C-ontario-m4b-1r4',
        'description': 'Detached House available for rent in East York.',
    },
    {
        'id': '42',
        'type': 'Property',
        'address': '1-2424 Howland Ave, Ottawa, Ontario K1G 1J5',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-2424-howland-ave%2C-ottawa%2C-ontario-k1g-1j5',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '43',
        'type': 'Basement Apartment',
        'address': '2-10 Peer St, Markham, Ontario L6B 0R1',
        'city': 'Markham',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-10-peer-st%2C-markham%2C-ontario-l6b-0r1',
        'description': 'Basement Apartment available for rent in Markham.',
    },
    {
        'id': '44',
        'type': 'Condo',
        'address': '709-134 York St, Ottawa, Ontario K1N 1K8',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/709-134-york-st%2C-ottawa%2C-ontario-k1n-1k8',
        'description': 'Condo available for rent in Ottawa.',
    },
    {
        'id': '45',
        'type': 'Property',
        'address': '1-44 Division St, Welland, Ontario L3B 3Z6',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1299',
        'beds': '0',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-44-division-st%2C-welland%2C-ontario-l3b-3z6',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '46',
        'type': 'Property',
        'address': '1-89 Enford Cres, Brampton, Ontario L7A 4C8',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '4',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-89-enford-cres%2C-brampton%2C-ontario-l7a-4c8',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '47',
        'type': 'Condo',
        'address': '504-280 Dundas St W, Toronto, Ontario M5T 1G2',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '4250',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/504-280-dundas-st-w%2C-toronto%2C-ontario-m5t-1g2',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '48',
        'type': 'Semi-Detached',
        'address': '35 Jay St, Brampton, Ontario L6Z 3V5',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2995',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/35-jay-st%2C-brampton%2C-ontario-l6z-3v5',
        'description': 'Semi-Detached available for rent in Brampton.',
    },
    {
        'id': '49',
        'type': 'Basement Apartment',
        'address': '2-542 Bartleman Terrace, Milton, Ontario L9T 6Z4',
        'city': 'Milton',
        'availability': 'For Lease',
        'price': '2095',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-542-bartleman-terrace%2C-milton%2C-ontario-l9t-6z4',
        'description': 'Basement Apartment available for rent in Milton.',
    },
    {
        'id': '50',
        'type': 'Townhouse',
        'address': '93 Gateland Dr, Barrie, Ontario L9J 0N2',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '2595',
        'beds': '3',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/93-gateland-dr%2C-barrie%2C-ontario-l9j-0n2',
        'description': 'Townhouse available for rent in Barrie.',
    },
    {
        'id': '51',
        'type': 'Basement Apartment',
        'address': '2-50 Gabrielle Crescent, Whitby, Ontario L1R 3M5',
        'city': 'Whitby',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-50-gabrielle-crescent%2C-whitby%2C-ontario-l1r-3m5',
        'description': 'Basement Apartment available for rent in Whitby.',
    },
    {
        'id': '52',
        'type': 'Basement Apartment',
        'address': '2-27 Bexley Crescent, York, Ontario M6N 2P6',
        'city': 'York',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-27-bexley-crescent%2C-york%2C-ontario-m6n-2p6',
        'description': 'Basement Apartment available for rent in York.',
    },
    {
        'id': '53',
        'type': 'Condo',
        'address': '57-226 Highview Ave W, London, Ontario N6J 4K1',
        'city': 'London',
        'availability': 'For Lease',
        'price': '2250',
        'beds': '3',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/57-226-highview-ave-w%2C-london%2C-ontario-n6j-4k1',
        'description': 'Condo available for rent in London.',
    },
    {
        'id': '54',
        'type': 'Basement Apartment',
        'address': '2-3910 Baggins Ct, Mississauga, Ontario L5N 7A2',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1750',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-3910-baggins-ct%2C-mississauga%2C-ontario-l5n-7a2',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '55',
        'type': 'Basement Apartment',
        'address': '2-38 Maple Crown Terrace, Barrie, Ontario L4M 7H4',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-38-maple-crown-terrace%2C-barrie%2C-ontario-l4m-7h4',
        'description': 'Basement Apartment available for rent in Barrie.',
    },
    {
        'id': '56',
        'type': 'Townhouse',
        'address': '224-755 Omega Drive, Pickering, Ontario L1V 0H1',
        'city': 'Pickering',
        'availability': 'For Lease',
        'price': '2350',
        'beds': '2',
        'baths': '3',
        'url': 'https://www.qterrapropertymanagement.com/properties/224-755-omega-drive%2C-pickering%2C-ontario-l1v-0h1',
        'description': 'Townhouse available for rent in Pickering.',
    },
    {
        'id': '57',
        'type': 'Property',
        'address': '206-1459 Trafalgar St, London, Ontario N5W 1W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1450',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/206-1459-trafalgar-st%2C-london%2C-ontario-n5w-1w8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '58',
        'type': 'Stacked Townhouse',
        'address': '43 Kingbird Cmn, Cambridge, Ontario N1R 5S2',
        'city': 'Cambridge',
        'availability': 'For Lease',
        'price': '2499',
        'beds': '4',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/43-kingbird-cmn%2C-cambridge%2C-ontario-n1r-5s2',
        'description': 'Stacked Townhouse available for rent in Cambridge.',
    },
    {
        'id': '59',
        'type': 'Basement Apartment',
        'address': '2-14 Cranston Manor Ct, Scarborough, Ontario M1J 3M6',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '1745',
        'beds': '2',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-14-cranston-manor-ct%2C-scarborough%2C-ontario-m1j-3m6',
        'description': 'Basement Apartment available for rent in Scarborough.',
    },
    {
        'id': '60',
        'type': 'Property',
        'address': '1-142 Brock St, Brockville, Ontario K6V 4G4',
        'city': 'Brockville',
        'availability': 'For Lease',
        'price': '1350',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-142-brock-st%2C-brockville%2C-ontario-k6v-4g4',
        'description': 'Property available for rent in Brockville.',
    },
    {
        'id': '61',
        'type': 'Property',
        'address': '3-234 King St W, Hamilton, Ontario L8P 1A9',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-234-king-st-w%2C-hamilton%2C-ontario-l8p-1a9',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '62',
        'type': 'Townhouse',
        'address': '5-1 Bond Crescent, Richmond Hill, Ontario L4E 1J4',
        'city': 'Richmond Hill',
        'availability': 'For Lease',
        'price': '2095',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/5-1-bond-crescent%2C-richmond-hill%2C-ontario-l4e-1j4',
        'description': 'Townhouse available for rent in Richmond Hill.',
    },
    {
        'id': '63',
        'type': 'Property',
        'address': '3-484 Main St E, Hamilton, Ontario L8N 1K6',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-484-main-st-e%2C-hamilton%2C-ontario-l8n-1k6',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '64',
        'type': 'Basement Apartment',
        'address': '2-4377 Violet Rd, Mississauga, Ontario L5V 1J8',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1550',
        'beds': '1',
        'baths': '4',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-4377-violet-rd%2C-mississauga%2C-ontario-l5v-1j8',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '65',
        'type': 'Property',
        'address': '1-149 Wilson Road South, Oshawa, Ontario L1H 6C2',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '3.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-149-wilson-road-south%2C-oshawa%2C-ontario-l1h-6c2',
        'description': 'Property available for rent in Oshawa.',
    },
    {
        'id': '66',
        'type': 'Basement Apartment',
        'address': '2-330 Arlington Ave, York, Ontario M6C 2Z9',
        'city': 'York',
        'availability': 'For Lease',
        'price': '1950',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-330-arlington-ave%2C-york%2C-ontario-m6c-2z9',
        'description': 'Basement Apartment available for rent in York.',
    },
    {
        'id': '67',
        'type': 'Apartment',
        'address': '202-350 Malaga Rd, Oshawa, Ontario L1J 1N7',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '2095',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/202-350-malaga-rd%2C-oshawa%2C-ontario-l1j-1n7',
        'description': 'Apartment available for rent in Oshawa.',
    },
    {
        'id': '68',
        'type': 'Condo',
        'address': '802-30 Elm Drive West, Mississauga, Ontario L5B 0N6',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2550',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/802-30-elm-drive-west%2C-mississauga%2C-ontario-l5b-0n6',
        'description': 'Condo available for rent in Mississauga.',
    },
    {
        'id': '69',
        'type': 'Townhouse',
        'address': '368 Moffatt Pond Ct, Ottawa, Ontario K2J 0C7',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2350',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/368-moffatt-pond-ct%2C-ottawa%2C-ontario-k2j-0c7',
        'description': 'Townhouse available for rent in Ottawa.',
    },
    {
        'id': '70',
        'type': 'Property',
        'address': '1-76 Ambleside Dr, Brampton, Ontario L6Y 1B9',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2595',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-76-ambleside-dr%2C-brampton%2C-ontario-l6y-1b9',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '71',
        'type': 'Townhouse',
        'address': '207-1335 Williamsport Dr, Mississauga, Ontario L4X 2S9',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2745',
        'beds': '2.5',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/207-1335-williamsport-dr%2C-mississauga%2C-ontario-l4x-2s9',
        'description': 'Townhouse available for rent in Mississauga.',
    },
    {
        'id': '72',
        'type': 'Basement Apartment',
        'address': '2-3895 Barley Trail, Mississauga, Ontario L5M 6N2',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-3895-barley-trail%2C-mississauga%2C-ontario-l5m-6n2',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '73',
        'type': 'Basement Apartment',
        'address': '2-56 Singhampton Rd, Vaughan, Ontario L4H 3Y5',
        'city': 'Vaughan',
        'availability': 'For Lease',
        'price': '1450',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-56-singhampton-rd%2C-vaughan%2C-ontario-l4h-3y5',
        'description': 'Basement Apartment available for rent in Vaughan.',
    },
    {
        'id': '74',
        'type': 'Detached House',
        'address': '18 Darrell Ave, Toronto, Ontario M4E 2G4',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '3395',
        'beds': '4',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/18-darrell-ave%2C-toronto%2C-ontario-m4e-2g4',
        'description': 'Detached House available for rent in Toronto.',
    },
    {
        'id': '75',
        'type': 'Basement Apartment',
        'address': '2-106 Reiner Rd, North York, Ontario M3H 2L6',
        'city': 'North York',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-106-reiner-rd%2C-north-york%2C-ontario-m3h-2l6',
        'description': 'Basement Apartment available for rent in North York.',
    },
    {
        'id': '76',
        'type': 'Basement Apartment',
        'address': '2-224 Taunton Rd W, Oshawa, Ontario L1G 3T3',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1195',
        'beds': '2',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-224-taunton-rd-w%2C-oshawa%2C-ontario-l1g-3t3',
        'description': 'Basement Apartment available for rent in Oshawa.',
    },
    {
        'id': '77',
        'type': 'Property',
        'address': '1B-1088 Gregg St, Ottawa, Ontario K1V 6G7',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '0',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1b-1088-gregg-st%2C-ottawa%2C-ontario-k1v-6g7',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '78',
        'type': 'Property',
        'address': 'A-124 Church St, Kitchener, Ontario N2G 2S4',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/a-124-church-st%2C-kitchener%2C-ontario-n2g-2s4',
        'description': 'Property available for rent in Kitchener.',
    },
    {
        'id': '79',
        'type': 'Condo',
        'address': '1211-12 Yonge St, Toronto, Ontario M5E 1Z9',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2799',
        'beds': '1.5',
        'baths': '3',
        'url': 'https://www.qterrapropertymanagement.com/properties/1211-12-yonge-st%2C-toronto%2C-ontario-m5e-1z9',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '80',
        'type': 'Detached House',
        'address': '12 Rudder Rd, Welland, Ontario L3B 0M5',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '4',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/12-rudder-rd%2C-welland%2C-ontario-l3b-0m5',
        'description': 'Detached House available for rent in Welland.',
    },
    {
        'id': '81',
        'type': 'Apartment',
        'address': '2-606 Chauncer Ave, Oshawa, Ontario L1H 3H4',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '0',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-606-chauncer-ave%2C-oshawa%2C-ontario-l1h-3h4',
        'description': 'Apartment available for rent in Oshawa.',
    },
    {
        'id': '82',
        'type': 'Apartment',
        'address': '2-6 Kings Point Dr, Etobicoke, Ontario M8Y 1Z4',
        'city': 'Etobicoke',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-6-kings-point-dr%2C-etobicoke%2C-ontario-m8y-1z4',
        'description': 'Apartment available for rent in Etobicoke.',
    },
    {
        'id': '83',
        'type': 'Detached House',
        'address': '74 Cassander Cres, Brampton, Ontario L6Z 1Z2',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2999',
        'beds': '4',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/74-cassander-cres%2C-brampton%2C-ontario-l6z-1z2',
        'description': 'Detached House available for rent in Brampton.',
    },
    {
        'id': '84',
        'type': 'Apartment',
        'address': '2915 Bur Oak Ave, Markham, Ontario L6B 1E6',
        'city': 'Markham',
        'availability': 'For Lease',
        'price': '2150',
        'beds': '2.5',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2915-bur-oak-ave%2C-markham%2C-ontario-l6b-1e6',
        'description': 'Apartment available for rent in Markham.',
    },
    {
        'id': '85',
        'type': 'Property',
        'address': '3-232 Lawrence Ave W, Toronto, Ontario M4R 2J3',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '3195',
        'beds': '3',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-232-lawrence-ave-w%2C-toronto%2C-ontario-m4r-2j3',
        'description': 'Property available for rent in Toronto.',
    },
    {
        'id': '86',
        'type': 'Detached House',
        'address': '5364 Glen Erin Dr, Mississauga, Ontario L5M 5C2',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '3995',
        'beds': '5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/5364-glen-erin-dr%2C-mississauga%2C-ontario-l5m-5c2',
        'description': 'Detached House available for rent in Mississauga.',
    },
    {
        'id': '87',
        'type': 'Property',
        'address': 'S3-376 Woodbine Ave, Toronto, Ontario M4L 3P6',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/s3-376-woodbine-ave%2C-toronto%2C-ontario-m4l-3p6',
        'description': 'Property available for rent in Toronto.',
    },
    {
        'id': '88',
        'type': 'Property',
        'address': '1-200 Chaffey St, Welland, Ontario L3B 2Y5',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1549',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-200-chaffey-st%2C-welland%2C-ontario-l3b-2y5',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '89',
        'type': 'Basement Apartment',
        'address': '2-547 Windfields Farm Dr W, Oshawa, Ontario L1H 7K4',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-547-windfields-farm-dr-w%2C-oshawa%2C-ontario-l1h-7k4',
        'description': 'Basement Apartment available for rent in Oshawa.',
    },
    {
        'id': '90',
        'type': 'Property',
        'address': '1-2 Quinlan Rd, Barrie, Ontario L4M 7A9',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '2595',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-2-quinlan-rd%2C-barrie%2C-ontario-l4m-7a9',
        'description': 'Property available for rent in Barrie.',
    },
    {
        'id': '91',
        'type': 'Property',
        'address': '1-27 Murchison Crescent, Etobicoke, Ontario M9V 3P5',
        'city': 'Etobicoke',
        'availability': 'For Lease',
        'price': '2650',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-27-murchison-crescent%2C-etobicoke%2C-ontario-m9v-3p5',
        'description': 'Property available for rent in Etobicoke.',
    },
    {
        'id': '92',
        'type': 'Basement Apartment',
        'address': '2-86 Taylor Dr, Barrie, Ontario L4N 8K3',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-86-taylor-dr%2C-barrie%2C-ontario-l4n-8k3',
        'description': 'Basement Apartment available for rent in Barrie.',
    },
    {
        'id': '93',
        'type': 'Basement Apartment',
        'address': '2-24 Pindar Crescent, North York, Ontario M2J 3L4',
        'city': 'North York',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-24-pindar-crescent%2C-north-york%2C-ontario-m2j-3l4',
        'description': 'Basement Apartment available for rent in North York.',
    },
    {
        'id': '94',
        'type': 'Property',
        'address': '3-32 Brock St W, Oshawa, Ontario L1G 1R4',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '2295',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-32-brock-st-w%2C-oshawa%2C-ontario-l1g-1r4',
        'description': 'Property available for rent in Oshawa.',
    },
    {
        'id': '95',
        'type': 'Basement Apartment',
        'address': '2-2688 Sapphire Dr, Pickering, Ontario L1X 0G5',
        'city': 'Pickering',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '3',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-2688-sapphire-dr%2C-pickering%2C-ontario-l1x-0g5',
        'description': 'Basement Apartment available for rent in Pickering.',
    },
    {
        'id': '96',
        'type': 'Basement Apartment',
        'address': '2-600 Bradley Dr, Whitby, Ontario L1N 6W3',
        'city': 'Whitby',
        'availability': 'For Lease',
        'price': '1750',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-600-bradley-dr%2C-whitby%2C-ontario-l1n-6w3',
        'description': 'Basement Apartment available for rent in Whitby.',
    },
    {
        'id': '97',
        'type': 'Property',
        'address': '692B Crystal St, Ottawa, Ontario K1K 2G2',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2150',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/692b-crystal-st%2C-ottawa%2C-ontario-k1k-2g2',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '98',
        'type': 'Basement Apartment',
        'address': '2-19 Grandwood Ave, Whitchurch-Stouffville, Ontario L4A 0M6',
        'city': 'Whitchurch-Stouffville',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-19-grandwood-ave%2C-whitchurch-stouffville%2C-ontario-l4a-0m6',
        'description': 'Basement Apartment available for rent in Whitchurch-Stouffville.',
    },
    {
        'id': '99',
        'type': 'Property',
        'address': '306-1459 Trafalgar St, London, Ontario N5W 1W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1425',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/306-1459-trafalgar-st%2C-london%2C-ontario-n5w-1w8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '100',
        'type': 'Property',
        'address': '1-18 Thirty Third Street, Etobicoke, Ontario M8W 3G9',
        'city': 'Etobicoke',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '2',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-18-thirty-third-street%2C-etobicoke%2C-ontario-m8w-3g9',
        'description': 'Property available for rent in Etobicoke.',
    },
    {
        'id': '101',
        'type': 'Property',
        'address': '1-22 Cumberland Dr, Brampton, Ontario L6V 1W6',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-22-cumberland-dr%2C-brampton%2C-ontario-l6v-1w6',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '102',
        'type': 'Apartment',
        'address': '3-255 Country Glen Rd, Markham, Ontario L6B 1C3',
        'city': 'Markham',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '0',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-255-country-glen-rd%2C-markham%2C-ontario-l6b-1c3',
        'description': 'Apartment available for rent in Markham.',
    },
    {
        'id': '103',
        'type': 'Condo',
        'address': '520-7437 Kingston Rd, Scarborough, Ontario M1B 0E9',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '1875',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/520-7437-kingston-rd%2C-scarborough%2C-ontario-m1b-0e9',
        'description': 'Condo available for rent in Scarborough.',
    },
    {
        'id': '104',
        'type': 'Property',
        'address': '1-58 Rollingwood Dr, Brampton, Ontario L6Y 5R1',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '4',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-58-rollingwood-dr%2C-brampton%2C-ontario-l6y-5r1',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '105',
        'type': 'Property',
        'address': '1-83 Hammond Rd, Mississauga, Ontario L5M 2A3',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '3',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-83-hammond-rd%2C-mississauga%2C-ontario-l5m-2a3',
        'description': 'Property available for rent in Mississauga.',
    },
    {
        'id': '106',
        'type': 'Property',
        'address': '216-1459 Trafalgar St, London, Ontario N5W 1W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1575',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/216-1459-trafalgar-st%2C-london%2C-ontario-n5w-1w8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '107',
        'type': 'Condo',
        'address': '2005-50 Grand Ave S, Cambridge, Ontario N1S 0C2',
        'city': 'Cambridge',
        'availability': 'For Lease',
        'price': '2499',
        'beds': '2',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2005-50-grand-ave-s%2C-cambridge%2C-ontario-n1s-0c2',
        'description': 'Condo available for rent in Cambridge.',
    },
    {
        'id': '108',
        'type': 'Basement Apartment',
        'address': '2-2409 Bankside Dr, Mississauga, Ontario L5M 6E6',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1450',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-2409-bankside-dr%2C-mississauga%2C-ontario-l5m-6e6',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '109',
        'type': 'Condo',
        'address': '406-10 Morrison St, Toronto, Ontario M5V 2T8',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2750',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/406-10-morrison-st%2C-toronto%2C-ontario-m5v-2t8',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '110',
        'type': 'Condo',
        'address': '612-1440 Clarriage Ct, Milton, Ontario L9T 2X5',
        'city': 'Milton',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/612-1440-clarriage-ct%2C-milton%2C-ontario-l9t-2x5',
        'description': 'Condo available for rent in Milton.',
    },
    {
        'id': '111',
        'type': 'Semi-Detached',
        'address': '98 Canter Blvd, Nepean, Ontario K2G 2M7',
        'city': 'Nepean',
        'availability': 'For Lease',
        'price': '2450',
        'beds': '3',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/98-canter-blvd%2C-nepean%2C-ontario-k2g-2m7',
        'description': 'Semi-Detached available for rent in Nepean.',
    },
    {
        'id': '112',
        'type': 'Property',
        'address': '1-60 Normandy Crescent, Richmond Hill, Ontario L4C 8L7',
        'city': 'Richmond Hill',
        'availability': 'For Lease',
        'price': '2995',
        'beds': '4',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-60-normandy-crescent%2C-richmond-hill%2C-ontario-l4c-8l7',
        'description': 'Property available for rent in Richmond Hill.',
    },
    {
        'id': '113',
        'type': 'Condo',
        'address': '111-1103 Jalna Blvd, London, Ontario N6E 2W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1699',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/111-1103-jalna-blvd%2C-london%2C-ontario-n6e-2w8',
        'description': 'Condo available for rent in London.',
    },
    {
        'id': '114',
        'type': 'Property',
        'address': '1-71 Chamomile Dr, Hamilton, Ontario L8W 0C1',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '3',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-71-chamomile-dr%2C-hamilton%2C-ontario-l8w-0c1',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '115',
        'type': 'Townhouse',
        'address': '267-60 Parrotta Dr, Toronto, Ontario M9M 0E5',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2499',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/267-60-parrotta-dr%2C-toronto%2C-ontario-m9m-0e5',
        'description': 'Townhouse available for rent in Toronto.',
    },
    {
        'id': '116',
        'type': 'Stacked Townhouse',
        'address': '4-823 Stirling Ave S, Kitchener, Ontario N2M 3K4',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '1999',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/4-823-stirling-ave-s%2C-kitchener%2C-ontario-n2m-3k4',
        'description': 'Stacked Townhouse available for rent in Kitchener.',
    },
    {
        'id': '117',
        'type': 'Apartment',
        'address': '101-350 Malaga Rd, Oshawa, Ontario L1J 1N7',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1950',
        'beds': '2',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/101-350-malaga-rd%2C-oshawa%2C-ontario-l1j-1n7',
        'description': 'Apartment available for rent in Oshawa.',
    },
    {
        'id': '118',
        'type': 'Basement Apartment',
        'address': '2-37 Ash Crescent, Etobicoke, Ontario M8W 1E4',
        'city': 'Etobicoke',
        'availability': 'For Lease',
        'price': '1599',
        'beds': '1',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-37-ash-crescent%2C-etobicoke%2C-ontario-m8w-1e4',
        'description': 'Basement Apartment available for rent in Etobicoke.',
    },
    {
        'id': '119',
        'type': 'Condo',
        'address': '2405-284 King St E, Toronto, Ontario M5A 1K4',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2750',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2405-284-king-st-e%2C-toronto%2C-ontario-m5a-1k4',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '120',
        'type': 'Apartment',
        'address': '6-164 Main St, Ottawa, Ontario K1S 1C2',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/6-164-main-st%2C-ottawa%2C-ontario-k1s-1c2',
        'description': 'Apartment available for rent in Ottawa.',
    },
    {
        'id': '121',
        'type': 'Apartment',
        'address': '3-1052 Barton St E, Hamilton, Ontario L8L 3E5',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-1052-barton-st-e%2C-hamilton%2C-ontario-l8l-3e5',
        'description': 'Apartment available for rent in Hamilton.',
    },
    {
        'id': '122',
        'type': 'Basement Apartment',
        'address': '2-1 Radley St, Woodbridge, Ontario L4L 8J7',
        'city': 'Woodbridge',
        'availability': 'For Lease',
        'price': '1899',
        'beds': '1',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-1-radley-st%2C-woodbridge%2C-ontario-l4l-8j7',
        'description': 'Basement Apartment available for rent in Woodbridge.',
    },
    {
        'id': '123',
        'type': 'Property',
        'address': '1-177 Colborne St, London, Ontario N6B 2S3',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1899',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-177-colborne-st%2C-london%2C-ontario-n6b-2s3',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '124',
        'type': 'Condo',
        'address': '726-86 Dundas St E, Mississauga, Ontario L5A 0B1',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2195',
        'beds': '1.5',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/726-86-dundas-st-e%2C-mississauga%2C-ontario-l5a-0b1',
        'description': 'Condo available for rent in Mississauga.',
    },
    {
        'id': '125',
        'type': 'Basement Apartment',
        'address': '2-22 Vandervoort Dr, Richmond Hill, Ontario L4E 0C6',
        'city': 'Richmond Hill',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '2',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-22-vandervoort-dr%2C-richmond-hill%2C-ontario-l4e-0c6',
        'description': 'Basement Apartment available for rent in Richmond Hill.',
    },
    {
        'id': '126',
        'type': 'Property',
        'address': '1-210 Armstrong St, Ottawa, Ontario K1Y 2W4',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1950',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-210-armstrong-st%2C-ottawa%2C-ontario-k1y-2w4',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '127',
        'type': 'Condo',
        'address': '413-58 Sky Harbour Dr, Brampton, Ontario L6Y 6J1',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2295',
        'beds': '2',
        'baths': '3.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/413-58-sky-harbour-dr%2C-brampton%2C-ontario-l6y-6j1',
        'description': 'Condo available for rent in Brampton.',
    },
    {
        'id': '128',
        'type': 'Apartment',
        'address': '4-208 Clarence St., Ottawa, Ontario K1N 5R1',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1950',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/4-208-clarence-st.%2C-ottawa%2C-ontario-k1n-5r1',
        'description': 'Apartment available for rent in Ottawa.',
    },
    {
        'id': '129',
        'type': 'Condo',
        'address': '2711-3525 Kariya Dr, Mississauga, Ontario L5B 0C2',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2399',
        'beds': '2',
        'baths': '3.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2711-3525-kariya-dr%2C-mississauga%2C-ontario-l5b-0c2',
        'description': 'Condo available for rent in Mississauga.',
    },
    {
        'id': '130',
        'type': 'Basement Apartment',
        'address': '2-12 Prairie Grass Cres, East Gwillimbury, Ontario L9N 0S8',
        'city': 'East Gwillimbury',
        'availability': 'For Lease',
        'price': '1995',
        'beds': '2',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-12-prairie-grass-cres%2C-east-gwillimbury%2C-ontario-l9n-0s8',
        'description': 'Basement Apartment available for rent in East Gwillimbury.',
    },
    {
        'id': '131',
        'type': 'Property',
        'address': '62 Bassett Cres, Brampton, Ontario L6X 0E4',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '3395',
        'beds': '5.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/62-bassett-cres%2C-brampton%2C-ontario-l6x-0e4',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '132',
        'type': 'Semi-Detached',
        'address': '1168 Prestonwood Crescent, Mississauga, Ontario L5V 2V3',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '3699',
        'beds': '4.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1168-prestonwood-crescent%2C-mississauga%2C-ontario-l5v-2v3',
        'description': 'Semi-Detached available for rent in Mississauga.',
    },
    {
        'id': '133',
        'type': 'Condo',
        'address': '3009-50 Absolute Ave, Mississauga, Ontario L4Z 0A9',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1999',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/3009-50-absolute-ave%2C-mississauga%2C-ontario-l4z-0a9',
        'description': 'Condo available for rent in Mississauga.',
    },
    {
        'id': '134',
        'type': 'Basement Apartment',
        'address': '2-52 Pennsylvania Ave, Brampton, Ontario L6Y 4P2',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-52-pennsylvania-ave%2C-brampton%2C-ontario-l6y-4p2',
        'description': 'Basement Apartment available for rent in Brampton.',
    },
    {
        'id': '135',
        'type': 'Apartment',
        'address': '8-6 Kings Point Dr, Etobicoke, Ontario M8Y 1Z4',
        'city': 'Etobicoke',
        'availability': 'For Lease',
        'price': '2099',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/8-6-kings-point-dr%2C-etobicoke%2C-ontario-m8y-1z4',
        'description': 'Apartment available for rent in Etobicoke.',
    },
    {
        'id': '136',
        'type': 'Basement Apartment',
        'address': '2-68 Mossgrove Crescent, Brampton, Ontario L7A 3W4',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '3',
        'baths': '5.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-68-mossgrove-crescent%2C-brampton%2C-ontario-l7a-3w4',
        'description': 'Basement Apartment available for rent in Brampton.',
    },
    {
        'id': '137',
        'type': 'Basement Apartment',
        'address': '2-76 William Honey Crescent, Markham, Ontario L3S 2M1',
        'city': 'Markham',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-76-william-honey-crescent%2C-markham%2C-ontario-l3s-2m1',
        'description': 'Basement Apartment available for rent in Markham.',
    },
    {
        'id': '138',
        'type': 'Property',
        'address': '14-1007 Adelaide St N, London, Ontario N5Y 2M8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1475',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/14-1007-adelaide-st-n%2C-london%2C-ontario-n5y-2m8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '139',
        'type': 'Condo',
        'address': '1203-1 Jarvis St, Hamilton, Ontario L8R 3J2',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1203-1-jarvis-st%2C-hamilton%2C-ontario-l8r-3j2',
        'description': 'Condo available for rent in Hamilton.',
    },
    {
        'id': '140',
        'type': 'Condo',
        'address': '111-1100 Sheppard Ave W, North York, Ontario M3K 0E4',
        'city': 'North York',
        'availability': 'For Lease',
        'price': '2599',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/111-1100-sheppard-ave-w%2C-north-york%2C-ontario-m3k-0e4',
        'description': 'Condo available for rent in North York.',
    },
    {
        'id': '141',
        'type': 'Property',
        'address': '5-50 Nelson St W, Brampton, Ontario L6X 1C3',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '1295',
        'beds': '0',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/5-50-nelson-st-w%2C-brampton%2C-ontario-l6x-1c3',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '142',
        'type': 'Property',
        'address': '104-8 York St W, Ridgetown, Ontario N0P 2C0',
        'city': 'Ridgetown',
        'availability': 'For Lease',
        'price': '1699',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/104-8-york-st-w%2C-ridgetown%2C-ontario-n0p-2c0',
        'description': 'Property available for rent in Ridgetown.',
    },
    {
        'id': '143',
        'type': 'Condo',
        'address': '201-7277 Wilson Crescent, Niagara Falls, Ontario L2G 4R8',
        'city': 'Niagara Falls',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/201-7277-wilson-crescent%2C-niagara-falls%2C-ontario-l2g-4r8',
        'description': 'Condo available for rent in Niagara Falls.',
    },
    {
        'id': '144',
        'type': 'Property',
        'address': '212-244 King St, Welland, Ontario L3B 3J8',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1299',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/212-244-king-st%2C-welland%2C-ontario-l3b-3j8',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '145',
        'type': 'Property',
        'address': '7-44 Division St, Welland, Ontario L3B 3Z6',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1099',
        'beds': '0',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/7-44-division-st%2C-welland%2C-ontario-l3b-3z6',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '146',
        'type': 'Detached House',
        'address': '3036 Abernathy Way, Oakville, Ontario L6M 5C1',
        'city': 'Oakville',
        'availability': 'For Lease',
        'price': '3845',
        'beds': '5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3036-abernathy-way%2C-oakville%2C-ontario-l6m-5c1',
        'description': 'Detached House available for rent in Oakville.',
    },
    {
        'id': '147',
        'type': 'Property',
        'address': '108-244 King St, Welland, Ontario L3B 3J8',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1299',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/108-244-king-st%2C-welland%2C-ontario-l3b-3j8',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '148',
        'type': 'Basement Apartment',
        'address': '2-1153 Stag Holw, Oakville, Ontario L6M 5M4',
        'city': 'Oakville',
        'availability': 'For Lease',
        'price': '2195',
        'beds': '2',
        'baths': '4.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-1153-stag-holw%2C-oakville%2C-ontario-l6m-5m4',
        'description': 'Basement Apartment available for rent in Oakville.',
    },
    {
        'id': '149',
        'type': 'Basement Apartment',
        'address': '2-93 Stannardville Dr, Ajax, Ontario L1T 4P8',
        'city': 'Ajax',
        'availability': 'For Lease',
        'price': '1545',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-93-stannardville-dr%2C-ajax%2C-ontario-l1t-4p8',
        'description': 'Basement Apartment available for rent in Ajax.',
    },
    {
        'id': '150',
        'type': 'Apartment',
        'address': '5-284 St. Patrick St, Ottawa, Ontario K1N 5K5',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1699',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/5-284-st.-patrick-st%2C-ottawa%2C-ontario-k1n-5k5',
        'description': 'Apartment available for rent in Ottawa.',
    },
    {
        'id': '151',
        'type': 'Property',
        'address': '1-13 Tanglemere Crescent, Brampton, Ontario L7A 1R7',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2495',
        'beds': '3',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-13-tanglemere-crescent%2C-brampton%2C-ontario-l7a-1r7',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '152',
        'type': 'Condo',
        'address': '2712-15 Wellington Street South, Kitchener, Ontario N2G 0E4',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2712-15-wellington-street-south%2C-kitchener%2C-ontario-n2g-0e4',
        'description': 'Condo available for rent in Kitchener.',
    },
    {
        'id': '153',
        'type': 'Property',
        'address': '1-132 Manse Rd, Scarborough, Ontario M1E 3V1',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '2295',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-132-manse-rd%2C-scarborough%2C-ontario-m1e-3v1',
        'description': 'Property available for rent in Scarborough.',
    },
    {
        'id': '154',
        'type': 'Property',
        'address': '3-270 Carlton St, St. Catharines, Ontario L2N 1B8',
        'city': 'St. Catharines',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-270-carlton-st%2C-st.-catharines%2C-ontario-l2n-1b8',
        'description': 'Property available for rent in St. Catharines.',
    },
    {
        'id': '155',
        'type': 'Property',
        'address': '1-27 Hearne Crescent, Ajax, Ontario L1T 3P5',
        'city': 'Ajax',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '4',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-27-hearne-crescent%2C-ajax%2C-ontario-l1t-3p5',
        'description': 'Property available for rent in Ajax.',
    },
    {
        'id': '156',
        'type': 'Property',
        'address': '1-372 Kingsdale Ave, Oshawa, Ontario L1G 5H5',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-372-kingsdale-ave%2C-oshawa%2C-ontario-l1g-5h5',
        'description': 'Property available for rent in Oshawa.',
    },
    {
        'id': '157',
        'type': 'Property',
        'address': '104-1459 Trafalgar St, London, Ontario N5W 1W8',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '1',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/104-1459-trafalgar-st%2C-london%2C-ontario-n5w-1w8',
        'description': 'Property available for rent in London.',
    },
    {
        'id': '158',
        'type': 'Basement Apartment',
        'address': '2-1919 Evans Blvd, London, Ontario N6M 0K2',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1650',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-1919-evans-blvd%2C-london%2C-ontario-n6m-0k2',
        'description': 'Basement Apartment available for rent in London.',
    },
    {
        'id': '159',
        'type': 'Basement Apartment',
        'address': '2-10 Deverill Crescent, Ajax, Ontario L1T 1S4',
        'city': 'Ajax',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-10-deverill-crescent%2C-ajax%2C-ontario-l1t-1s4',
        'description': 'Basement Apartment available for rent in Ajax.',
    },
    {
        'id': '160',
        'type': 'Basement Apartment',
        'address': '7-1370 Killarney Beach Rd, Innisfil, Ontario L0L 1W0',
        'city': 'Innisfil',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/7-1370-killarney-beach-rd%2C-innisfil%2C-ontario-l0l-1w0',
        'description': 'Basement Apartment available for rent in Innisfil.',
    },
    {
        'id': '161',
        'type': 'Property',
        'address': '2-2443 PagÃ© Rd, Orleans, Ontario K1W 1H2',
        'city': 'Orleans',
        'availability': 'For Lease',
        'price': '2450',
        'beds': '3',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-2443-pagã©-rd%2C-orleans%2C-ontario-k1w-1h2',
        'description': 'Property available for rent in Orleans.',
    },
    {
        'id': '162',
        'type': 'Townhouse',
        'address': '247-1075 Douglas McCurdy Cmn, Mississauga, Ontario L5G 0C6',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2799',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/247-1075-douglas-mccurdy-cmn%2C-mississauga%2C-ontario-l5g-0c6',
        'description': 'Townhouse available for rent in Mississauga.',
    },
    {
        'id': '163',
        'type': 'Property',
        'address': '2-142 Brock St, Brockville, Ontario K6V 4G4',
        'city': 'Brockville',
        'availability': 'For Lease',
        'price': '1799',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-142-brock-st%2C-brockville%2C-ontario-k6v-4g4',
        'description': 'Property available for rent in Brockville.',
    },
    {
        'id': '164',
        'type': 'Basement Apartment',
        'address': '2-423 Mississauga Vly Blvd, Mississauga, Ontario L5A 1Y9',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1395',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-423-mississauga-vly-blvd%2C-mississauga%2C-ontario-l5a-1y9',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '165',
        'type': 'Basement Apartment',
        'address': '2-171 Sloane Ave, North York, Ontario M4A 2C2',
        'city': 'North York',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-171-sloane-ave%2C-north-york%2C-ontario-m4a-2c2',
        'description': 'Basement Apartment available for rent in North York.',
    },
    {
        'id': '166',
        'type': 'Property',
        'address': '3-1525 Barton St E, Hamilton, Ontario L8H 2X5',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1295',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-1525-barton-st-e%2C-hamilton%2C-ontario-l8h-2x5',
        'description': 'Property available for rent in Hamilton.',
    },
    {
        'id': '167',
        'type': 'Stacked Townhouse',
        'address': '3-823 Stirling Ave S, Kitchener, Ontario N2M 3K4',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '2299',
        'beds': '3',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/3-823-stirling-ave-s%2C-kitchener%2C-ontario-n2m-3k4',
        'description': 'Stacked Townhouse available for rent in Kitchener.',
    },
    {
        'id': '168',
        'type': 'Condo',
        'address': '1305-1171 Ambleside Dr, Ottawa, Ontario K2B 8E2',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2295',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1305-1171-ambleside-dr%2C-ottawa%2C-ontario-k2b-8e2',
        'description': 'Condo available for rent in Ottawa.',
    },
    {
        'id': '169',
        'type': 'Basement Apartment',
        'address': '2-1799 Appleview Rd, Pickering, Ontario L1V 1T7',
        'city': 'Pickering',
        'availability': 'For Lease',
        'price': '1750',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-1799-appleview-rd%2C-pickering%2C-ontario-l1v-1t7',
        'description': 'Basement Apartment available for rent in Pickering.',
    },
    {
        'id': '170',
        'type': 'Property',
        'address': '1-86 Gilchrist Ave, Ottawa, Ontario K1Y 0M8',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '2550',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-86-gilchrist-ave%2C-ottawa%2C-ontario-k1y-0m8',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '171',
        'type': 'Apartment',
        'address': '1-1052 Barton St E, Hamilton, Ontario L8L 3E5',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1749',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-1052-barton-st-e%2C-hamilton%2C-ontario-l8l-3e5',
        'description': 'Apartment available for rent in Hamilton.',
    },
    {
        'id': '172',
        'type': 'Detached House',
        'address': '24 Constellation Crescent, Richmond Hill, Ontario L4C 8J6',
        'city': 'Richmond Hill',
        'availability': 'For Lease',
        'price': '3150',
        'beds': '3',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/24-constellation-crescent%2C-richmond-hill%2C-ontario-l4c-8j6',
        'description': 'Detached House available for rent in Richmond Hill.',
    },
    {
        'id': '173',
        'type': 'Property',
        'address': '105-8 York St W, Ridgetown, Ontario N0P 2C0',
        'city': 'Ridgetown',
        'availability': 'For Lease',
        'price': '1675',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/105-8-york-st-w%2C-ridgetown%2C-ontario-n0p-2c0',
        'description': 'Property available for rent in Ridgetown.',
    },
    {
        'id': '174',
        'type': 'Property',
        'address': '261 Dixon St, Kitchener, Ontario N2G 3G1',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/261-dixon-st%2C-kitchener%2C-ontario-n2g-3g1',
        'description': 'Property available for rent in Kitchener.',
    },
    {
        'id': '175',
        'type': 'Condo',
        'address': '709-145 Hillcrest Ave, Mississauga, Ontario L5B 3Z1',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '2395',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/709-145-hillcrest-ave%2C-mississauga%2C-ontario-l5b-3z1',
        'description': 'Condo available for rent in Mississauga.',
    },
    {
        'id': '176',
        'type': 'Property',
        'address': '4-210 Armstrong St, Ottawa, Ontario K1Y 2W4',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1795',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/4-210-armstrong-st%2C-ottawa%2C-ontario-k1y-2w4',
        'description': 'Property available for rent in Ottawa.',
    },
    {
        'id': '177',
        'type': 'Townhouse',
        'address': '115-1180 Mississauga Vly Blvd, Mississauga, Ontario L5A 3M9',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '3099',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/115-1180-mississauga-vly-blvd%2C-mississauga%2C-ontario-l5a-3m9',
        'description': 'Townhouse available for rent in Mississauga.',
    },
    {
        'id': '178',
        'type': 'Condo',
        'address': '528-1 Jarvis St, Hamilton, Ontario L8R 0A8',
        'city': 'Hamilton',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/528-1-jarvis-st%2C-hamilton%2C-ontario-l8r-0a8',
        'description': 'Condo available for rent in Hamilton.',
    },
    {
        'id': '179',
        'type': 'Apartment',
        'address': '2-208 Clarence St., Ottawa, Ontario K1N 5R1',
        'city': 'Ottawa',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-208-clarence-st.%2C-ottawa%2C-ontario-k1n-5r1',
        'description': 'Apartment available for rent in Ottawa.',
    },
    {
        'id': '180',
        'type': 'Basement Apartment',
        'address': '1-56 Garthdale Ct, Toronto, Ontario M3H 5P9',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '1895',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-56-garthdale-ct%2C-toronto%2C-ontario-m3h-5p9',
        'description': 'Basement Apartment available for rent in Toronto.',
    },
    {
        'id': '181',
        'type': 'Basement Apartment',
        'address': '2-4 Fordham Rd, Brampton, Ontario L6Y 0E4',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-4-fordham-rd%2C-brampton%2C-ontario-l6y-0e4',
        'description': 'Basement Apartment available for rent in Brampton.',
    },
    {
        'id': '182',
        'type': 'Condo',
        'address': '1012-60 Frederick St, Kitchener, Ontario N2H 0C7',
        'city': 'Kitchener',
        'availability': 'For Lease',
        'price': '1695',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1012-60-frederick-st%2C-kitchener%2C-ontario-n2h-0c7',
        'description': 'Condo available for rent in Kitchener.',
    },
    {
        'id': '183',
        'type': 'Townhouse',
        'address': '52 Commuter Dr, Brampton, Ontario L7A 0S5',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2699',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/52-commuter-dr%2C-brampton%2C-ontario-l7a-0s5',
        'description': 'Townhouse available for rent in Brampton.',
    },
    {
        'id': '184',
        'type': 'Property',
        'address': '1-52 Pennsylvania Ave, Brampton, Ontario L6Y 4P2',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2795',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-52-pennsylvania-ave%2C-brampton%2C-ontario-l6y-4p2',
        'description': 'Property available for rent in Brampton.',
    },
    {
        'id': '185',
        'type': 'Condo',
        'address': '116-3650 Kingston Rd, Scarborough, Ontario M1M 3X9',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '1975',
        'beds': '1',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/116-3650-kingston-rd%2C-scarborough%2C-ontario-m1m-3x9',
        'description': 'Condo available for rent in Scarborough.',
    },
    {
        'id': '186',
        'type': 'Condo',
        'address': '2205-284 King St E, Toronto, Ontario M5A 1K4',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '2',
        'baths': '2.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/2205-284-king-st-e%2C-toronto%2C-ontario-m5a-1k4',
        'description': 'Condo available for rent in Toronto.',
    },
    {
        'id': '187',
        'type': 'Property',
        'address': '1-66 Wantanopa Crescent, Scarborough, Ontario M1H 2B4',
        'city': 'Scarborough',
        'availability': 'For Lease',
        'price': '2375',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-66-wantanopa-crescent%2C-scarborough%2C-ontario-m1h-2b4',
        'description': 'Property available for rent in Scarborough.',
    },
    {
        'id': '188',
        'type': 'Condo',
        'address': '207-123 Maurice Dr, Oakville, Ontario L6K 2W6',
        'city': 'Oakville',
        'availability': 'For Lease',
        'price': '2699',
        'beds': '1.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/207-123-maurice-dr%2C-oakville%2C-ontario-l6k-2w6',
        'description': 'Condo available for rent in Oakville.',
    },
    {
        'id': '189',
        'type': 'Basement Apartment',
        'address': '2-43 Bernick Dr, Barrie, Ontario L4M 5C1',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '1475',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-43-bernick-dr%2C-barrie%2C-ontario-l4m-5c1',
        'description': 'Basement Apartment available for rent in Barrie.',
    },
    {
        'id': '190',
        'type': 'Property',
        'address': '4-200 Chaffey St, Welland, Ontario L3B 2Y5',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1495',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/4-200-chaffey-st%2C-welland%2C-ontario-l3b-2y5',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '191',
        'type': 'Basement Apartment',
        'address': '2-67 Apollo Rd, Markham, Ontario L3S 4H1',
        'city': 'Markham',
        'availability': 'For Lease',
        'price': '1595',
        'beds': '2',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-67-apollo-rd%2C-markham%2C-ontario-l3s-4h1',
        'description': 'Basement Apartment available for rent in Markham.',
    },
    {
        'id': '192',
        'type': 'Basement Apartment',
        'address': '2-724 Adelaide St N, London, Ontario N5Y 2L5',
        'city': 'London',
        'availability': 'For Lease',
        'price': '1299',
        'beds': '1',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-724-adelaide-st-n%2C-london%2C-ontario-n5y-2l5',
        'description': 'Basement Apartment available for rent in London.',
    },
    {
        'id': '193',
        'type': 'Property',
        'address': '207113 Hwy-9, Mono, Ontario L9W 1Y4',
        'city': 'Mono',
        'availability': 'For Lease',
        'price': '2599',
        'beds': '3',
        'baths': '1.5',
        'url': 'https://www.qterrapropertymanagement.com/properties/207113-hwy-9%2C-mono%2C-ontario-l9w-1y4',
        'description': 'Property available for rent in Mono.',
    },
    {
        'id': '194',
        'type': 'Basement Apartment',
        'address': '2-2 Quinlan Rd, Barrie, Ontario L4M 7A9',
        'city': 'Barrie',
        'availability': 'For Lease',
        'price': '1850',
        'beds': '2',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-2-quinlan-rd%2C-barrie%2C-ontario-l4m-7a9',
        'description': 'Basement Apartment available for rent in Barrie.',
    },
    {
        'id': '195',
        'type': 'Basement Apartment',
        'address': '2-3322 Greenbelt Cres, Mississauga, Ontario L5N 5X1',
        'city': 'Mississauga',
        'availability': 'For Lease',
        'price': '1745',
        'beds': '2.5',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/2-3322-greenbelt-cres%2C-mississauga%2C-ontario-l5n-5x1',
        'description': 'Basement Apartment available for rent in Mississauga.',
    },
    {
        'id': '196',
        'type': 'Detached House',
        'address': '4236 Terrace Ave, Niagara Falls, Ontario L2E 3J6',
        'city': 'Niagara Falls',
        'availability': 'For Lease',
        'price': '2295',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/4236-terrace-ave%2C-niagara-falls%2C-ontario-l2e-3j6',
        'description': 'Detached House available for rent in Niagara Falls.',
    },
    {
        'id': '197',
        'type': 'Stacked Townhouse',
        'address': '22 Westway Rd, Brampton, Ontario L7A 5M7',
        'city': 'Brampton',
        'availability': 'For Lease',
        'price': '2699',
        'beds': '3',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/22-westway-rd%2C-brampton%2C-ontario-l7a-5m7',
        'description': 'Stacked Townhouse available for rent in Brampton.',
    },
    {
        'id': '198',
        'type': 'Property',
        'address': '5-44 Division St, Welland, Ontario L3B 3Z6',
        'city': 'Welland',
        'availability': 'For Lease',
        'price': '1099',
        'beds': '0',
        'baths': '2',
        'url': 'https://www.qterrapropertymanagement.com/properties/5-44-division-st%2C-welland%2C-ontario-l3b-3z6',
        'description': 'Property available for rent in Welland.',
    },
    {
        'id': '199',
        'type': 'Property',
        'address': '1-12 Glebemount Ave, Toronto, Ontario M4C 3R3',
        'city': 'Toronto',
        'availability': 'For Lease',
        'price': '2695',
        'beds': '3',
        'baths': '1',
        'url': 'https://www.qterrapropertymanagement.com/properties/1-12-glebemount-ave%2C-toronto%2C-ontario-m4c-3r3',
        'description': 'Property available for rent in Toronto.',
    },
    {
        'id': '200',
        'type': 'Condo',
        'address': '4-359 Elgin Ct, Oshawa, Ontario L1J 2P4',
        'city': 'Oshawa',
        'availability': 'For Lease',
        'price': '2095',
        'beds': '1',
        'baths': '3',
        'url': 'https://www.qterrapropertymanagement.com/properties/4-359-elgin-ct%2C-oshawa%2C-ontario-l1j-2p4',
        'description': 'Condo available for rent in Oshawa.',
    },
]


def search_properties(location: str = None, property_type: str = None):
    """Return up to 3 available (non-Leased) properties matching the filters."""
    results = [p for p in PROPERTIES if p.get('availability', '').lower() != 'leased']
    if location:
        results = [p for p in results if location.lower() in p['address'].lower()
                   or location.lower() in p['city'].lower()]
    if property_type:
        results = [p for p in results if property_type.lower() in p['type'].lower()]
    return results[-2:]  # Return 2 latest matches
